name: 'Build'

on: push

jobs:
  test-ruby:
    runs-on: ubuntu-latest
    container:
      image: getterminus/ruby-ci-image:2.6-je-20190205
    steps:
      - name: Pull
        uses: actions/checkout@v2
      - run: |
          bundle check --path=/usr/local/bundle || bundle --local --path=/usr/local/bundle
          bundle exec rspec
